config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get '/about', to: 'pages#about'
  get '/prices', to: 'pages#prices'
  post '/prices', to: 'pages#prices'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home

  	require 'net/http'
  	require 'json'

  	#Gets news API data
  	@url = 'https://min-api.cryptocompare.com/data/v2/news/?lang=EN'
  	@uri = URI(@url)
  	@response = Net::HTTP.get(@uri)
  	@news = JSON.parse(@response)

  	#Gets prices API data
   	@prices_url = 'https://min-api.cryptocompare.com/data/pricemultifull?fsyms=BTC,ETH,XRP,USDT,LTC,LINK,BCH,ADA,DOT,BNB&tsyms=USD'
  	@prices_uri = URI(@prices_url)
  	@prices_response = Net::HTTP.get(@prices_uri)
  	@prices = JSON.parse(@prices_response)

  end

  def about
  end

  def prices

  	require 'net/http'
  	require 'json'
  	@symbol = params[:sym]

  	if @symbol
	  	#Search field API data check
	   	@search_url = 'https://min-api.cryptocompare.com/data/pricemultifull?fsyms=' + @symbol + '&tsyms=USD'
	  	@search_uri = URI(@search_url)
	  	@search_response = Net::HTTP.get(@search_uri)
	  	@search = JSON.parse(@search_response)
	  end


  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to "Coin Blog", root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "About | ", about_path, class: "nav-link" %>
      </li>  
      <li class="nav-item">
        <%= link_to "Check Coin | ", prices_path, class: "nav-link" %>
      </li>    
    </ul>
    <%= form_tag prices_path, :method => 'POST', class: "form-inline my-2 my-lg-0" %>
    <%= text_field_tag 'sym', nil, placeholder: 'Put a symbol!', class: "form-control mr-sm-2" %>
    <%= submit_tag 'Lookup', class: "btn btn-outline-secondary my-2 my-sm-0" %>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>tmt-blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <br>
      <div class="container">
      <%= render 'layouts/navbar' %>
      </div>
    </header>
    <main>
      <br>
      <div class="container">
      <%= yield %>
      </div>
    </main>
    <footer>
      <br>
      <div class="container">
      </div>
    </footer>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/home.html.erb
<table class="table table-sm table-striped table-bordered table-hover">
  <thead class="thead-dark">
  	<tr>
      <th scope="col">Name</th>
      <th scope="col">Price</th>
      <th scope="col">24h High</th>
      <th scope="col">24h Low</th>
      <th scope="col">Market</th>
    </tr>
	</thead>
  <tbody>
  	<% @prices["DISPLAY"].each do |key, value| %>	
    <tr>
      <td><%= key %></td>
      <td><%= value["USD"]["PRICE"] %></td>
      <td><%= value["USD"]["HIGHDAY"] %></td>
      <td><%= value["USD"]["LOWDAY"] %></td>
      <td><%= value["USD"]["MKTCAP"] %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<div class="container">
	<div class="row">
		<% for x in @news["Data"] %>
			<div class="col-sm">	
				<div class="card" style="width: 20rem;">
				  <img src="<%= x["imageurl"] %>" class="card-img-top" alt="<%= x["source"] %>">
				  <div class="card-body">
				  	<h5 class="card-title"><%= x["title"] %></h5>
				    <p class="card-text"><%= x["body"] %></p>
				    <a href="<%= x["url"] %>" class="btn btn-secondary">Read more...</a>
				  </div>
				</div>
				<br>
		</div>
		<% end %>
	</div>
</div>
		

app/views/pages/prices.html.erb
<% if @symbol %>	
	<% if @search["Response"] %>
		<h4>That symbol <%= Symbol %> doesnt exist, try again...</h4>
	<% else %>

		<% @search["DISPLAY"].each do |key, value| %>
			<div class="jumbotron">
			  <h1 class="display-4"><%= key %> </h1>
			  Price: <%= value["USD"]["PRICE"] %><br>
			  24hr High: <%= value["USD"]["HIGHDAY"] %><br>
			  24hr Low: <%= value["USD"]["LOWDAY"] %><br>
			  Marketcap: <%= value["USD"]["MKTCAP"] %><br>
			</div>	
		<% end %>
	<% end %>	
<% else %>
	<h4>Please enter a crypto symbol in the form above...</h4>
<% end %>